-- =============================================================================
-- SUPERSEDED by 0003_fix_role_guard_and_promote.sql — do not run this.
--
-- This version failed with:
--   ERROR: P0001: changing role is not permitted
--
-- The guard in 0001 was SECURITY DEFINER and depended on auth.uid(), which is
-- NULL in the SQL Editor. It therefore blocked the promotion it was meant to
-- protect. 0003 fixes the guard and performs the promotion in one script.
-- =============================================================================
