-- =============================================================================
-- Fit Compas — 0015: notifications (feature 15)
--
-- Run once in Supabase Studio -> SQL Editor -> New query -> Run.
-- Idempotent: running it twice is safe.
--
-- Two tables, and the split between them is the whole design.
--
--   `notification_messages` is what the trainer *composed*: text in three
--   languages, who it goes to described as a rule ("everyone with a live
--   plan"), and when — once, every day, or on chosen weekdays.
--
--   `notifications` is what somebody *received*: one row per person per
--   occurrence, with the text already resolved into their language and frozen.
--
-- The obvious cheaper shape is one table plus a join at read time. It breaks on
-- the second day. An audience is a rule, and rules change under you: a client
-- who finishes their plan on Tuesday would silently drop out of the audience of
-- Monday's message and lose a notification they had already read. Freezing the
-- delivery is also what keeps the text stable — the trainer fixing a typo in a
-- weekly reminder must not rewrite what went out last week.
--
-- Same reason the text is copied rather than referenced: `notifications.title`
-- is a plain string in one language, not jsonb. The recipient's language is
-- decided once, at delivery, from `profiles.locale`. A message delivered in
-- Serbian stays Serbian even if they later switch the app to English, which is
-- the honest thing — that is the notification they got.
--
-- **Email is a column, not a second table.** `email_status` on the delivered
-- row is the queue: dispatch inserts rows as `queued`, a later pass takes the
-- queued ones and marks them `sent` or `failed`. One table means a delivery and
-- its email can never disagree about whether they exist, and the retry story is
-- `where email_status = 'queued'` rather than a reconciliation.
-- =============================================================================

-- ---------- enums -----------------------------------------------------------

do $$
begin
  -- Where a notification came from. `announcement` and `reminder` are both
  -- written by the trainer and differ only in how they read; `plan` and
  -- `system` are generated by the app and have no message row behind them.
  if not exists (select 1 from pg_type where typname = 'notification_kind') then
    create type public.notification_kind as enum (
      'announcement',
      'reminder',
      'plan',
      'system'
    );
  end if;

  -- Audience as a rule rather than a stored list of ids: the trainer picks
  -- "everyone who has gone quiet" once and it keeps meaning that next week.
  -- Resolved to ids at every dispatch, in lib/notifications/audience.ts.
  if not exists (select 1 from pg_type where typname = 'notification_audience') then
    create type public.notification_audience as enum (
      'all',          -- every client account
      'active_plan',  -- has a live assignment (active or paused)
      'no_plan',      -- has none
      'idle',         -- no finished session in the last 14 days
      'one'           -- a single client, in audience_user_id
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'notification_repeat') then
    create type public.notification_repeat as enum ('once', 'daily', 'weekly');
  end if;

  if not exists (select 1 from pg_type where typname = 'notification_message_status') then
    create type public.notification_message_status as enum (
      'scheduled',  -- waiting for next_run_at
      'paused',     -- the trainer stopped it; keeps its schedule
      'sent',       -- a one-off that has gone out, or a repeat past its end
      'cancelled'
    );
  end if;

  -- 'none' rather than a nullable column: a row that was never meant to send
  -- an email and a row whose email state is unknown are different things, and
  -- the queue query has to be able to tell them apart.
  if not exists (select 1 from pg_type where typname = 'notification_email_status') then
    create type public.notification_email_status as enum (
      'none',
      'queued',
      'sent',
      'failed'
    );
  end if;
end
$$;

-- ---------- messages --------------------------------------------------------

create table if not exists public.notification_messages (
  id            uuid primary key default gen_random_uuid(),

  author_id     uuid references public.profiles (id) on delete set null,

  kind          public.notification_kind not null default 'announcement',

  -- jsonb keyed by locale, the same shape every other authored text in this
  -- schema uses (see src/db/schema/i18n.ts). Serbian is the source; a missing
  -- locale falls back through `translate()` at delivery.
  title         jsonb not null default '{}'::jsonb,
  body          jsonb not null default '{}'::jsonb,

  -- Where tapping it goes, as a locale-less app path (`/plan`, `/progress`).
  -- The language segment is prefixed at render, so one stored value works for
  -- a reader in any of the three.
  href          text,

  audience         public.notification_audience not null default 'all',
  audience_user_id uuid references public.profiles (id) on delete cascade,

  repeat_mode   public.notification_repeat not null default 'once',

  -- Local wall time, plus the zone it is wall time *in*. Storing an instant
  -- instead would move a 09:00 reminder to 10:00 the day the clocks change,
  -- which is exactly when a habit is most fragile.
  time_of_day   time,
  time_zone     text not null default 'Europe/Belgrade',

  -- ISO weekdays, 1 = Monday .. 7 = Sunday. Only read when repeat_mode is
  -- 'weekly'.
  repeat_days   smallint[] not null default '{}',

  starts_on     date,
  ends_on       date,

  via_email     boolean not null default false,

  status        public.notification_message_status not null default 'scheduled',

  -- The cursor. Everything above describes the schedule; this is the one
  -- mutable field dispatch reads and advances, so "what is due" is an index
  -- scan and not a recomputation over every message in the table.
  next_run_at   timestamptz,
  last_run_at   timestamptz,
  run_count     integer not null default 0,

  -- How many inbox rows the last run produced. Shown in the list, because a
  -- message that reached nobody otherwise looks identical to one that reached
  -- everybody.
  last_recipients integer not null default 0,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  -- A single-recipient message needs its recipient, and no other audience may
  -- carry one — otherwise a later edit could leave a stale id pointing at
  -- somebody who then quietly starts receiving a broadcast.
  constraint notification_messages_audience_target check (
    (audience = 'one' and audience_user_id is not null)
    or (audience <> 'one' and audience_user_id is null)
  ),

  -- A repeat without a time of day has nothing to fire on.
  constraint notification_messages_repeat_time check (
    repeat_mode = 'once' or time_of_day is not null
  ),

  constraint notification_messages_window check (
    starts_on is null or ends_on is null or ends_on >= starts_on
  ),

  constraint notification_messages_weekdays check (
    repeat_mode <> 'weekly'
    or (array_length(repeat_days, 1) between 1 and 7
        and repeat_days <@ array[1,2,3,4,5,6,7]::smallint[])
  )
);

comment on table public.notification_messages is
  'What the trainer composed and how it should go out. Feature 15.';

-- The only hot read: what is due now. Partial, because a table of finished and
-- cancelled messages should cost nothing to skip.
create index if not exists notification_messages_due_idx
  on public.notification_messages (next_run_at)
  where status = 'scheduled' and next_run_at is not null;

create index if not exists notification_messages_recent_idx
  on public.notification_messages (created_at desc);

drop trigger if exists notification_messages_touch_updated_at on public.notification_messages;
create trigger notification_messages_touch_updated_at
  before update on public.notification_messages
  for each row execute function public.touch_updated_at();

-- ---------- deliveries ------------------------------------------------------

create table if not exists public.notifications (
  id           uuid primary key default gen_random_uuid(),

  user_id      uuid not null references public.profiles (id) on delete cascade,

  -- Null for system notifications with no composed message behind them, and
  -- for a delivery whose message the trainer later deleted. `set null` rather
  -- than `cascade`: deleting a schedule must not reach into somebody's inbox
  -- and remove things they have already read.
  message_id   uuid references public.notification_messages (id) on delete set null,

  kind         public.notification_kind not null default 'announcement',

  -- Resolved at delivery, in `locale`. See the header.
  title        text not null,
  body         text not null default '',
  href         text,
  locale       text,

  -- Which firing of a repeating message this is — the occurrence's calendar day
  -- in the message's zone, or 'once'. Half of the idempotency key below.
  occurrence_key text not null default 'once',

  email_status  public.notification_email_status not null default 'none',
  email_error   text,
  email_sent_at timestamptz,

  read_at      timestamptz,
  created_at   timestamptz not null default now()
);

comment on table public.notifications is
  'One delivered notification, text already resolved into the reader language. Feature 15.';

-- Idempotency, and the reason dispatch can be triggered from more than one
-- place without coordination. A cron tick, a "send now" click and a page load
-- racing each other all try to insert the same three columns; the first wins
-- and the rest are `on conflict do nothing`. Without this, a single Vercel cron
-- retry would double every message.
create unique index if not exists notifications_occurrence_key
  on public.notifications (message_id, user_id, occurrence_key)
  where message_id is not null;

-- The inbox: newest first, per person.
create index if not exists notifications_inbox_idx
  on public.notifications (user_id, created_at desc);

-- The badge in the header, on every page load of the client app. Partial so it
-- stays the size of the unread set rather than of the whole history.
create index if not exists notifications_unread_idx
  on public.notifications (user_id)
  where read_at is null;

-- The email queue.
create index if not exists notifications_email_queue_idx
  on public.notifications (created_at)
  where email_status = 'queued';

-- ---------- RLS -------------------------------------------------------------
--
-- Verify before pushing:
--   curl -H "apikey: $PUBLISHABLE_KEY" \
--        "$SUPABASE_URL/rest/v1/notifications?select=*"
--   curl -H "apikey: $PUBLISHABLE_KEY" \
--        "$SUPABASE_URL/rest/v1/notification_messages?select=*"
-- Both must return [].
--
-- Read-only for everyone, including the owner. Every write in this feature goes
-- through a Server Action on a connection that bypasses RLS, so there is no
-- legitimate PostgREST write to allow — and "mark as read" is not worth an
-- update policy that would also let a client rewrite the title of a message
-- their trainer sent them.
--
-- `notification_messages` is admin-only in both directions: an audience rule
-- names segments of the client list ("everyone who has gone quiet"), which is
-- the trainer's read of their roster and not something a client should be able
-- to enumerate.

alter table public.notifications          enable row level security;
alter table public.notification_messages  enable row level security;

drop policy if exists "notifications_own"           on public.notifications;
drop policy if exists "notifications_admin"         on public.notifications;
drop policy if exists "notification_messages_admin" on public.notification_messages;

create policy "notifications_own" on public.notifications
  for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "notifications_admin" on public.notifications
  for select to authenticated
  using (public.is_admin());

create policy "notification_messages_admin" on public.notification_messages
  for select to authenticated
  using (public.is_admin());
